### ISSUE TITLE
Request to Add @throws Annotations to PHP SDK

### ISSUE THREAD

**Issue by AJenbo** [AltaPay/sdk-php#3]
While using the SDK, I noticed that it would benefit from the inclusion of @throws annotations in the PHPDoc blocks. This would enhance error detection and improve our overall experience when working with the SDK.

For example, when we invoke `Altapay::capture()`, it internally calls `CaptureReservation::call()`. However, there is no indication in the documentation that an `Altapay\Exceptions\ClientException` may be thrown during this process.

To address this, I suggest adding `@throws` annotations to the relevant PHPDoc blocks throughout the SDK. This would not only improve our ability to catch and handle exceptions effectively but also align with best practices in code documentation.

You can configure the following PHPStan settings to finding places where `@throws` have been omitted.
```yml
    exceptions:
        check:
            missingCheckedExceptionInThrows: true
            tooWideThrowType: true
```

This will go a long way in improving the usability and reliability of code that makes use of the SDK. Thank you for your consideration.
